#!/usr/bin/env python3
"""
Renders the EXACT conversation annotate.py sends to the teacher, as readable markdown.

Built from the same `build_messages()` the annotation job calls, so this cannot drift
from what actually runs -- if you change prompts.py, re-run this and the file updates.
Use it to review the prompt before burning a GPU hour, and to diff two prompt versions.

It does NOT load the model, the weights or the images (images are shown as their file
paths). No GPU, no network, seconds to run.

Usage:
    # the real thing, with your five actual few-shot blocks
    python -m mocs_annotation.dump_prompt \
        --fewshot   $OUT/fewshot.json \
        --selection $OUT/selection.json \
        --out       mocs_annotation/PROMPT.md

    # just the system turn, no data files needed
    python -m mocs_annotation.dump_prompt --system-only
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from mocs_annotation.prompts import build_messages, build_system_prompt, prompt_fingerprint

# 1,204,224 px cap / (patch 16^2 x merge 2^2 = 1024 px per token). Matches
# annotate.py::DEFAULT_MAX_PIXELS.
VISION_TOKENS_PER_IMAGE = 1176


class _ImageRef:
    """Stands in for a PIL image so the dump shows a path instead of an object."""

    def __init__(self, label: str):
        self.label = label

    def __repr__(self) -> str:
        return self.label


def render(messages: List[Dict[str, Any]]) -> str:
    out: List[str] = []
    for i, msg in enumerate(messages):
        out.append(f"### `[{i:>2}]` role: `{msg['role']}`\n")
        for part in msg["content"]:
            if part["type"] == "image":
                out.append(f"**\\<IMAGE\\>** `{part['image']}` "
                           f"*(expands to ~{VISION_TOKENS_PER_IMAGE} vision tokens)*\n")
            else:
                # FOUR backticks on the outside. The assistant turns are themselves
                # ```json fenced blocks, and a markdown fence only closes on a run of
                # equal-or-greater length -- with three, the inner fence would close
                # the outer one and the rest of the turn would render as prose.
                out.append("````text\n" + part["text"] + "\n````\n")
        out.append("")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fewshot", default=None, help="fewshot.json from build_fewshot.py")
    ap.add_argument("--selection", default=None, help="selection.json, for a real query record")
    ap.add_argument("--record-index", type=int, default=0, help="Which selection record to render")
    ap.add_argument("--box-hints", action="store_true",
                     help="Render with the MOCS box hints on (off by default, matching annotate.py)")
    ap.add_argument("--out", default=None, help="Write markdown here instead of stdout")
    ap.add_argument("--system-only", action="store_true", help="Print just the system turn and exit")
    args = ap.parse_args()

    if args.system_only:
        print(build_system_prompt())
        return

    fewshot: List[Dict[str, Any]] = []
    if args.fewshot:
        with open(args.fewshot, "r", encoding="utf-8") as f:
            fewshot = json.load(f)
    fewshot_images = [_ImageRef(e.get("image_file", "<missing>")) for e in fewshot]

    record: Optional[Dict[str, Any]] = None
    query_label = "<the MOCS query image>"
    if args.selection:
        with open(args.selection, "r", encoding="utf-8") as f:
            sel = json.load(f)
        record = sel["records"][args.record_index]
        query_label = f"{sel['manifest'].get('images_root', '')}/{record['file_name']}"

    messages = build_messages(
        query_image=_ImageRef(query_label),
        record=record,
        fewshot=fewshot,
        fewshot_images=fewshot_images,
        include_box_hints=args.box_hints,
    )

    n_images = sum(1 for m in messages for c in m["content"] if c["type"] == "image")
    text_chars = sum(len(c.get("text", "")) for m in messages for c in m["content"])
    vision_tokens = n_images * VISION_TOKENS_PER_IMAGE
    approx_text_tokens = text_chars // 4

    header = [
        "# The exact prompt sent to the annotator",
        "",
        "Generated by `python -m mocs_annotation.dump_prompt` from "
        "`mocs_annotation/prompts.py::build_messages` -- the same function "
        "`annotate.py` calls, so this is what actually runs.",
        "",
        "| | |",
        "|---|---|",
        f"| messages | {len(messages)} |",
        f"| images | {n_images} ({len(fewshot)} few-shot + 1 query) |",
        f"| vision tokens | ~{vision_tokens} |",
        f"| text chars / approx tokens | {text_chars} / ~{approx_text_tokens} |",
        f"| **approx total input** | **~{vision_tokens + approx_text_tokens} tokens** |",
        f"| box hints | {'ON' if args.box_hints else 'OFF (default)'} |",
        f"| contract sha256 | `{prompt_fingerprint(fewshot)[:16]}` |",
        "",
        "Decoding: `max_new_tokens=1024`, `do_sample=False` (greedy), "
        "`repetition_penalty=1.05`. No truncation -- the query image is last, so "
        "right-truncation would drop the image being annotated.",
        "",
        "---",
        "",
    ]

    body = "\n".join(header) + render(messages)

    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8")
        print(f"Wrote {out}  ({len(messages)} messages, {n_images} images, "
              f"~{vision_tokens + approx_text_tokens} input tokens)")
    else:
        print(body)


if __name__ == "__main__":
    main()
